import { randomBytes, createHash } from "node:crypto";
import { join, resolve, dirname } from "node:path";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

export const LOOPBACK_ADDRESS = "127.0.0.1";

export interface MediaMtxConfigOptions {
  rtspUrl: string;
  path: string;
  apiToken: string;
  webrtcToken: string;
  rtmpToken: string;
  srtToken: string;
  httpPort: number;
  rtspPort: number;
  rtspPortOut?: number;
  rtmpPort: number;
  webrtcUdpPort?: number;
  configDir: string;
  recordPath?: string;
  sourceOnDemand?: boolean;
  configFileName?: string;
  readTimeoutMs?: number;
  writeTimeoutMs?: number;
}

export interface MediaMtxConfigResult {
  configPath: string;
  httpPort: number;
  rtspPort: number;
  apiToken: string;
  webrtcToken: string;
  rtmpToken: string;
  srtToken: string;
}

export function generateSessionTokens(): {
  apiToken: string;
  webrtcToken: string;
  rtmpToken: string;
  srtToken: string;
} {
  const token = (): string => randomBytes(24).toString("base64url");
  return {
    apiToken: token(),
    webrtcToken: token(),
    rtmpToken: token(),
    srtToken: token(),
  };
}

export function generateMediaMtxConfig(
  options: MediaMtxConfigOptions,
): MediaMtxConfigResult {
  const configDir = resolve(options.configDir);
  mkdirSync(configDir, { recursive: true });
  const configFileName = options.configFileName ?? "mediamtx.yml";
  const configPath = join(configDir, configFileName);
  const logFileName = configFileName.replace(/\.ya?ml$/i, ".log");

  const readTimeoutMs = options.readTimeoutMs ?? 10_000;
  const writeTimeoutMs = options.writeTimeoutMs ?? 10_000;
  const webrtcUdpPort = options.webrtcUdpPort ?? options.httpPort + 2;
  const viewerUser = "viewer";
  const apiUser = "api";

  const config = [
    `# Generated by Simple DVR Wi-Fi. Loopback only.`,
    `logLevel: warn`,
    `logDestinations: [file]`,
    `logFile: ${join(configDir, logFileName)}`,
    `readTimeout: ${readTimeoutMs}ms`,
    `writeTimeout: ${writeTimeoutMs}ms`,
    ``,
    `authMethod: internal`,
    `authInternalUsers:`,
    `  - user: ${viewerUser}`,
    `    pass: ${options.webrtcToken}`,
    `    ips: ["127.0.0.1", "::1"]`,
    `    permissions:`,
    `      - action: read`,
    `        path: ${options.path}`,
    `  - user: ${apiUser}`,
    `    pass: ${options.apiToken}`,
    `    ips: ["127.0.0.1", "::1"]`,
    `    permissions:`,
    `      - action: api`,
    ``,
    `rtsp: true`,
    `rtspTransports: [tcp]`,
    `rtspAddress: ${LOOPBACK_ADDRESS}:${options.rtspPort}`,
    ``,
    `rtmp: false`,
    `rtmpAddress: ${LOOPBACK_ADDRESS}:${options.rtmpPort}`,
    `hls: false`,
    `srt: false`,
    `moq: false`,
    `playback: false`,
    `metrics: false`,
    `pprof: false`,
    ``,
    `webrtc: true`,
    `webrtcAddress: ${LOOPBACK_ADDRESS}:${options.httpPort}`,
    `webrtcEncryption: false`,
    `webrtcAllowOrigins: ["*"]`,
    `webrtcLocalUDPAddress: ${LOOPBACK_ADDRESS}:${webrtcUdpPort}`,
    `webrtcLocalTCPAddress: ""`,
    `webrtcIPsFromInterfaces: false`,
    `webrtcAdditionalHosts: [${LOOPBACK_ADDRESS}]`,
    ``,
    `api: true`,
    `apiAddress: ${LOOPBACK_ADDRESS}:${options.httpPort + 1}`,
    ``,
    `paths:`,
    `  ${options.path}:`,
    `    source: ${JSON.stringify(options.rtspUrl)}`,
    `    sourceOnDemand: ${options.sourceOnDemand ?? true}`,
    `    sourceOnDemandStartTimeout: 10s`,
    `    sourceOnDemandCloseAfter: 10s`,
    `    rtspTransport: tcp`,
    `    record: false`,
    ...(options.recordPath
      ? [
          `    recordPath: ${JSON.stringify(options.recordPath)}`,
          `    recordFormat: fmp4`,
          `    recordPartDuration: 1s`,
          `    recordSegmentDuration: 15m`,
          `    recordDeleteAfter: 0s`,
        ]
      : []),
    ``,
  ].join("\n");

  writeFileSync(configPath, config, "utf8");
  return {
    configPath,
    httpPort: options.httpPort,
    rtspPort: options.rtspPort,
    apiToken: `${apiUser}:${options.apiToken}`,
    webrtcToken: `${viewerUser}:${options.webrtcToken}`,
    rtmpToken: options.rtmpToken,
    srtToken: options.srtToken,
  };
}

export interface MediaBinaryManifestEntry {
  id: string;
  platform: string;
  fileName: string;
  version: string | null;
  origin: string | null;
  license: string;
  fileSha256: string | null;
  status: string;
}

export function loadMediaBinaryManifest(
  manifestPath: string,
  platform = process.platform,
): MediaBinaryManifestEntry | null {
  let raw: string;
  try {
    raw = readFileSync(manifestPath, "utf8");
  } catch {
    return null;
  }
  const parsed = JSON.parse(raw) as { components: MediaBinaryManifestEntry[] };
  return (
    parsed.components.find(
      (component) =>
        component.id === "mediamtx" && component.platform === platform,
    ) ?? null
  );
}

export function expectedMediaMtxHashFromManifest(manifestPath: string): string {
  const override = process.env.MEDIAMTX_EXPECTED_SHA256;
  if (override) return override;
  const entry = loadMediaBinaryManifest(manifestPath);
  if (!entry || entry.status !== "approved") return "";
  return entry.fileSha256 ?? "";
}

export function mediaMtxManifestPath(resourcesRoot: string): string {
  return join(resolve(resourcesRoot), "media-binaries.json");
}

export function sha256OfFile(contents: Buffer): string {
  return createHash("sha256").update(contents).digest("hex");
}

export function mediaMtxBinaryPath(
  resourcesRoot: string,
  platform = process.platform,
): string {
  const base = resolve(resourcesRoot);
  const executable = platform === "win32" ? "mediamtx.exe" : "mediamtx";
  return join(base, "mediamtx", platform, executable);
}

export function sanitizeConfigDir(configDir: string): string {
  return dirname(resolve(configDir));
}
